
services:

  eotvos.versenyr.password_generator:
    class: Eotvos\VersenyrBundle\Extension\PasswordGenerator
    calls:
      - [ setContainer, [@service_container] ]

  eotvos.versenyr.mailer.user:
    class: Eotvos\VersenyrBundle\Mailer\UserMailer
    calls:
      - [ setContainer, [@service_container] ]

  eotvos.versenyr.usertype.dummy:
    class: Eotvos\VersenyrBundle\UserType\DummyType
    tags:
      - { name: eotvos.versenyr.registrationtype }

  eotvos.versenyr.roundtype.finals:
    class: Eotvos\VersenyrBundle\RoundType\FinalsType
    tags:
      - { name: eotvos.versenyr.roundtype }

  eotvos.versenyr.round.finals:
    class: Eotvos\VersenyrBundle\Controller\FinalsController
    calls:
      - [ setContainer, [@service_container] ]

  eotvos.versenyr.cwm.module:
    class:  Eotvos\VersenyrBundle\Cwm\VersenyrModule
    tags:
      - { name: cancellar.cwm }

  eotvos.versenyr.registrationregistry:
    class: Eotvos\VersenyrBundle\DependencyInjection\Registry\ModuleRegistry

  eotvos.versenyr.roundregistry:
    class: Eotvos\VersenyrBundle\DependencyInjection\Registry\ModuleRegistry

  eotvos.versenyr.resultregistry:
    class: Eotvos\VersenyrBundle\DependencyInjection\Registry\ModuleRegistry

  EotvosBundle.twig.ecvurl:
    class: Eotvos\VersenyrBundle\Extension\EcvUrlExtension
    tags:
      - { name: twig.extension }
    calls: 
      - [ setContainer,  [@service_container] ] 

  EotvosBundle.twig.configuration:
    class: Eotvos\VersenyrBundle\Extension\ConfigurationExtension
    tags:
      - { name: twig.extension }
    calls: 
      - [ setContainer,  [@service_container] ] 

  eotvos.versenyr.results.public:
    class: Eotvos\VersenyrBundle\ResultType\PublicResults
    calls:
      - [ setContainer, [@service_container] ]
    tags:
      - { name: eotvos.versenyr.resulttype }

  eotvos.versenyr.results.private:
    class: Eotvos\VersenyrBundle\ResultType\PrivateResults
    calls:
      - [ setContainer, [@service_container] ]
    tags:
      - { name: eotvos.versenyr.resulttype }

  eotvos.versenyr.results.nopoint:
    class: Eotvos\VersenyrBundle\ResultType\NopointResults
    calls:
      - [ setContainer, [@service_container] ]
    tags:
      - { name: eotvos.versenyr.resulttype }

