
services:

  eotvos.versenyr.password_generator:
    class: Eotvos\VersenyrBundle\Extension\PasswordGenerator
    calls:
      - [ setContainer, [@service_container] ]

  eotvos.versenyr.mailer.user:
    class: Eotvos\VersenyrBundle\Mailer\UserMailer
    calls:
      - [ setContainer, [@service_container] ]

  eotvos.versenyr.usertype.dummy:
    class: Eotvos\VersenyrBundle\UserType\DummyType
    tags:
      - { name: eotvos.versenyr.registrationtype }

  eotvos.versenyr.roundtype.finals:
    class: Eotvos\VersenyrBundle\RoundType\FinalsType
    tags:
      - { name: eotvos.versenyr.roundtype }

  eotvos.versenyr.cwm.module:
    class:  Eotvos\VersenyrBundle\Cwm\VersenyrModule
    tags:
      - { name: cancellar.cwm }

  eotvos.versenyr.registrationregistry:
    class: Eotvos\VersenyrBundle\DependencyInjection\Registry\ModuleRegistry

  eotvos.versenyr.roundregistry:
    class: Eotvos\VersenyrBundle\DependencyInjection\Registry\ModuleRegistry
