
services:

  eotvos_versenyr.round.upload:
    class: Eotvos\VersenyrBundle\Controller\UploadRoundController
    calls:
      - [ setContainer, [@service_container] ]
    tags:
      - { name: eotvos.versenyr.roundtype }

  eotvos_versenyr.round.quiz:
    class: Eotvos\VersenyrBundle\Controller\QuizRoundController
    calls:
      - [ setContainer, [@service_container] ]
    tags:
      - { name: eotvos.versenyr.roundtype }

  eotvos_versenyr.round.infocontest:
    class: Eotvos\VersenyrBundle\Controller\InfocontestRoundController
    calls:
      - [ setContainer, [@service_container] ]
    tags:
      - { name: eotvos.versenyr.roundtype }

  eotvos.versenyr.password_generator:
    class: Eotvos\VersenyrBundle\Extension\PasswordGenerator
    calls:
      - [ setContainer, [@service_container] ]

  eotvos.versenyr.mailer.user:
    class: Eotvos\VersenyrBundle\Mailer\UserMailer
    calls:
      - [ setContainer, [@service_container] ]

  eotvos.versenyr.usertype.dummy:
    class: Eotvos\VersenyrBundle\UserType\DummyType
    tags:
      - { name: eotvos.versenyr.usertype }
