
services:

  eotvos.versenyr.password_generator:
    class: Eotvos\VersenyrBundle\Extension\PasswordGenerator
    calls:
      - [ setContainer, [@service_container] ]

  eotvos.versenyr.mailer.user:
    class: Eotvos\VersenyrBundle\Mailer\UserMailer
    calls:
      - [ setContainer, [@service_container] ]

  eotvos.versenyr.usertype.dummy:
    class: Eotvos\VersenyrBundle\UserType\DummyType
    tags:
      - { name: eotvos.versenyr.usertype }

  eotvos.versenyr.cwm.module:
    class:  Eotvos\VersenyrBundle\Cwm\VersenyrModule
    tags:
      - { name: cancellar.cwm }

