<?php

namespace Eotvos\VersenyrBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RoundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoundRepository extends EntityRepository
{
    /**
     * Returns rounds with at least one user submission.
     * 
     * @return void
     */
    public function getSubmittedRounds()
    {
        return $this->getEntityManager()->createQuery('SELECT r.id, p.title, pp.title AS section, COUNT(DISTINCT s.user_id) AS cnt FROM Eotvos\VersenyrBundle\Entity\Round r JOIN r.submissions s JOIN r.page p JOIN p.parent pp GROUP BY r.id HAVING COUNT(s.id) > 0')->getResult();
    }

}
