<?php

namespace Eotvos\VersenyrBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TermRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermRepository extends EntityRepository
{
    /**
     * Returns the root page of a term
     * 
     * @return Term
     */
    public function getLastTerm()
    {
        try {
            $term = $this->getEntityManager()
                ->createQuery('SELECT t FROM EotvosVersenyrBundle:Term t WHERE t.active = true ORDER BY t.registrationStart DESC')
                ->getResult();

            return $term[0];
        } catch (\Doctrine\ORM\NoResultException $nre) {
            return null;
        } catch (\Doctrine\ORM\NonUniqueResultException $nure) {
            throw $nure;
        }
    }

}
