<?php

namespace Eotvos\VersenyrBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * Return the list of the contensants : not including admins and testers
     * 
     * @return array
     */
    public function getAllContensants()
    {
        return $this
            ->getEntityManager()
            ->createQuery('SELECT u.* FROM Eotvos\VersenyrBundle\Entity\User u WHERE u.admin=0 AND u.tester=0')->getResult();
    }
}
