<?php

namespace Cancellar\TrackerBundle\Logger;


/**
 * Interface required by a logger implementation.
 *
 * A class intetnded for service cancellar.tracker.logger must fully implement this interface.
 *
 * @author Zsolt Parragi <zsolt.parragi@cancellar.hu>
 * @since 0.1
 * @version 0.1
 */
interface TrackerLoggerInterface
{
    /**
     * Generates a new log entry with the given parameters.
     *
     * sessUuid should be set if tracker id found in both cookie and session but differs.
     *
     * @param string $uuid An unique string identifying the client
     * @param bool $inCookie Found identifier in cookie
     * @param bool $inSession Found identifier in session
     * @param string $ip IP address of the client
     * @param string $hostname Hostname address of the client
     * @param datetime $date request time
     * @param string $userAgent useragent string of the request
     * @param string $sessUuid session uuid, if uuid in session and cookie differs, otherwise null
     * @param string infoTag optional string describing the category of the visit
     *
     */
    public function log($uuid, $inCookie, $inSession, $ip, $hostname, \DateTime $date, $userAgent, $sessUuid, $infoTag=null);

    /**
     * Loads all log entries for the given uuid.
     *
     * List is generated by uuid and sessUuid fields.
     *
     * @returns array
     */
    public function getInfoForUuid($uuid);

    /**
     * Loads all log entries for the given ip address.
     *
     * List is generated by ip address.
     *
     * @returns array
     */
    public function getInfoForIp($ip);

}

